### ISSUE TITLE
implement mqtt lwt 

### ISSUE THREAD

**Issue by sumnerboy12** [caitken-com/OXRS-IO-Web-TouchPanel#9]
when you connect to the broker you send it your lwt topic and payload - OXRS standard is `stat/<clientid>/lwt` and `{ "online": false }`

then when the connection is lost or the client goes offline, the broker will send the lwt payload to that topic so anyone listening will know if has gone offline.

the second part is to publish `{ "online": true }` from your code when you successfully connect to the broker - effectively the opposite of lwt, i.e. telling anyone listening you are alive. this is what a lot of us are using to trigger NodeRED flows to publish config payloads to `conf/<clientid>` - i.e. dynamically provision config when a device comes online.

**Comment by caitken-com** [comment]
Done 👌
